# Generated by Django 2.2.4 on 2019-08-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codingbus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='author',
            new_name='teacher',
        ),
    ]
